{{- if .Values.operator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-operator-sa
  namespace: {{ .Release.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-operator-role
  namespace: {{ .Release.namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-operator-role-binding
  namespace: {{ .Release.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-operator-sa
  namespace: {{ .Release.namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-operator-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
